package com.briefflow.unit.entity;

import com.briefflow.entity.Workspace;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class WorkspaceTest {

    @Test
    void should_setTimestamps_when_onCreate() {
        Workspace workspace = new Workspace();
        workspace.setName("Agencia Criativa Digital");
        workspace.onCreate();

        assertNotNull(workspace.getCreatedAt());
        assertNotNull(workspace.getUpdatedAt());
        // slug is NOT set by onCreate — it must be set by the service layer
        assertNull(workspace.getSlug());
    }

    @Test
    void should_updateTimestamp_when_onUpdate() {
        Workspace workspace = new Workspace();
        workspace.setName("Agencia Original");
        workspace.onCreate();

        workspace.setName("Novo Nome");
        workspace.onUpdate();

        assertNotNull(workspace.getUpdatedAt());
        // slug is NOT regenerated by onUpdate — it must be set by the service layer
        assertNull(workspace.getSlug());
    }

    @Test
    void should_generateSlug_when_simpleNameProvided() {
        String slug = Workspace.generateSlug("Agencia Criativa Digital");
        assertEquals("agencia-criativa-digital", slug);
    }

    @Test
    void should_handleSpecialChars_when_generatingSlug() {
        String slug = Workspace.generateSlug("Café & Design Ltda.");
        assertEquals("cafe-design-ltda", slug);
    }

    @Test
    void should_transliterateAccents_when_generatingSlug() {
        String slug = Workspace.generateSlug("Agência Criação & Design");
        assertEquals("agencia-criacao-design", slug);
    }
}
